Smite cmd
provsalt/LightningDeath pull request #20
Opened 2023-01-24 09:11 UTC by Endermanbugzjfc

2023-01-24 10:13 UTC, Endermanbugzjfc commented
# Beyond!
- Smite console.
- Entity selectors. (Colab with [EasyCommandAutoFill](https://poggit.pmmp.io/p/EasyCommandAutofill/3.0.2))

[Screencast from Tuesday, January 24, 2023 06:22:23 PM HKT.webm](https://user-images.githubusercontent.com/53002741/214272719-fd65e1b7-6f75-49fc-86f4-aeec915764c2.webm)

2023-01-24 10:30 UTC, Endermanbugzjfc commented
Update: Horrifying message format. is working now.

2023-01-24 10:53 UTC, Endermanbugzjfc commented
> # Beyond!
> * Smite console.
> * Entity selectors. (Colab with [EasyCommandAutoFill](https://poggit.pmmp.io/p/EasyCommandAutofill/3.0.2))
> 
>  Screencast.from.Tuesday.January.24.2023.06.22.23.PM.HKT.webm

Note: typo fixed at d7067f0.

2023-01-24 14:23 UTC, Endermanbugzjfc commented
# [PHAR direct link](https://poggit.pmmp.io/r/199691/LightningDeath_pr-30.phar)
*If you trust me.*

2023-01-24 15:00 UTC, DaisukeDaisuke approved these changes
LGTM

2023-01-28 03:10 UTC, provsalt requested changes
There are a few changes that should be changed.

2023-01-28 03:10 UTC, provsalt commented on src/Loader.php
> +    public function onCommand(CommandSender $sender, Command $command, string $alias, array $args) : bool {
I would move this to a Command class

2023-01-28 03:10 UTC, provsalt commented on src/Loader.php
> +                                     .eeeeeeeee
Unnecessary spam

2023-01-28 03:10 UTC, provsalt commented on src/Loader.php
> +               $sender->sendMessage("$arg who?");
I would prefer if the message would be a proper sentence.

2023-01-28 03:10 UTC, provsalt commented on src/Loader.php
> +        $sender->sendMessage(TextFormat::BOLD . TextFormat::ITALIC . TextFormat::DARK_RED . "Little $doThose $countArgs know what's gonna happen...");
Hmm. Is this necessary?

2023-03-15 03:28 UTC, closed without merging